import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for documentation.
 *
 * Uses autogenerated sidebars from the guides/, usage/, specs/ and decisions/
 * directories. The _category_.json files in each subdirectory control ordering
 * and labels; a page's `sidebar_position` orders it within its directory.
 */
const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
  usageSidebar: [
    {
      type: 'autogenerated',
      dirName: 'usage',
    },
  ],
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
