import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars configuration for documentation.
 *
 * Uses autogenerated sidebars from the specs/ and decisions/ directories.
 * The _category_.json files in each subdirectory control ordering and labels.
 */
const sidebars: SidebarsConfig = {
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
