// Command spdxgen regenerates internal/agentpkg/spdx_list.go, the vendored
// SPDX License List the package.toml license validator checks IDs against.
// It fetches json/licenses.json and json/exceptions.json from
// https://github.com/spdx/license-list-data at one tagged release and writes
// the license and exception IDs as sorted Go string slices, with a header
// recording the pinned version and the source URL.
//
// The list is vendored, never fetched at runtime: validation must be
// reproducible from a Harness version alone and must work offline, the same
// reason the scan's pattern table is compiled in. Bumping it is a reviewed
// diff: change -version on the go:generate line in license.go and run
// `go generate ./internal/agentpkg`.
//
// Governing: ADR-0044 (agent package stables), SPEC-0026 REQ-3 (manifest
// schema: [package].license).
//
// @joestump-agent 10/09/2026 - Added for harness#932.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

const rawBase = "https://raw.githubusercontent.com/spdx/license-list-data"

type licenseList struct {
	Version     string `json:"licenseListVersion"`
	ReleaseDate string `json:"releaseDate"`
	Licenses    []struct {
		ID string `json:"licenseId"`
	} `json:"licenses"`
}

type exceptionList struct {
	Version    string `json:"licenseListVersion"`
	Exceptions []struct {
		ID string `json:"licenseExceptionId"`
	} `json:"exceptions"`
}

func main() {
	version := flag.String("version", "", "license-list-data release tag, e.g. v3.29.0")
	out := flag.String("out", "spdx_list.go", "output Go file")
	flag.Parse()
	if *version == "" {
		fail(fmt.Errorf("-version is required"))
	}

	var lic licenseList
	if err := fetchJSON(*version, "licenses.json", &lic); err != nil {
		fail(err)
	}
	var exc exceptionList
	if err := fetchJSON(*version, "exceptions.json", &exc); err != nil {
		fail(err)
	}
	if lic.Version != exc.Version || "v"+lic.Version != *version {
		fail(fmt.Errorf("version mismatch: tag %s, licenses %s, exceptions %s", *version, lic.Version, exc.Version))
	}

	var licIDs, excIDs []string
	for _, l := range lic.Licenses {
		licIDs = append(licIDs, l.ID)
	}
	for _, e := range exc.Exceptions {
		excIDs = append(excIDs, e.ID)
	}
	if len(licIDs) == 0 || len(excIDs) == 0 {
		fail(fmt.Errorf("empty list: %d licenses, %d exceptions", len(licIDs), len(excIDs)))
	}
	sort.Strings(licIDs)
	sort.Strings(excIDs)

	released := lic.ReleaseDate
	if t, err := time.Parse(time.RFC3339, released); err == nil {
		released = t.Format("2006-01-02")
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by internal/agentpkg/internal/spdxgen; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "// SPDX License List %s (released %s), vendored from\n", lic.Version, released)
	fmt.Fprintf(&b, "// https://github.com/spdx/license-list-data/tree/%s/json\n", *version)
	fmt.Fprintf(&b, "// (licenses.json and exceptions.json). Regenerate with\n")
	fmt.Fprintf(&b, "// `go generate ./internal/agentpkg` after bumping -version in license.go.\n\n")
	fmt.Fprintf(&b, "package agentpkg\n\n")
	fmt.Fprintf(&b, "// SPDXListVersion is the pinned SPDX License List version license IDs\n")
	fmt.Fprintf(&b, "// validate against.\n")
	fmt.Fprintf(&b, "const SPDXListVersion = %q\n\n", lic.Version)
	writeList(&b, "spdxLicenseIDs", "every SPDX license ID on the list, deprecated ones included", licIDs)
	writeList(&b, "spdxExceptionIDs", "every SPDX license exception ID, valid after WITH", excIDs)

	src, err := format.Source(b.Bytes())
	if err != nil {
		fail(fmt.Errorf("format: %w", err))
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("spdxgen: wrote %s: SPDX %s, %d licenses, %d exceptions\n", *out, lic.Version, len(licIDs), len(excIDs))
}

func writeList(b *bytes.Buffer, name, doc string, ids []string) {
	fmt.Fprintf(b, "// %s is %s.\n", name, doc)
	fmt.Fprintf(b, "var %s = []string{\n", name)
	for _, id := range ids {
		fmt.Fprintf(b, "\t%q,\n", id)
	}
	fmt.Fprintf(b, "}\n\n")
}

func fetchJSON(version, file string, v any) error {
	url := strings.Join([]string{rawBase, version, "json", file}, "/")
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(url)
	if err != nil {
		return fmt.Errorf("fetch %s: %w", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetch %s: %s", url, resp.Status)
	}
	raw, err := io.ReadAll(io.LimitReader(resp.Body, 16<<20))
	if err != nil {
		return fmt.Errorf("read %s: %w", url, err)
	}
	if err := json.Unmarshal(raw, v); err != nil {
		return fmt.Errorf("decode %s: %w", url, err)
	}
	return nil
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "spdxgen: %v\n", err)
	os.Exit(1)
}
