#!/usr/bin/env node
// Copy the hand-authored docs (../../docs/guides/*.md and ../../docs/usage/*.md)
// into the generated Docusaurus docs tree (build output). The sdd-content plugin
// owns ../docs-generated but only writes decisions/, specs/, index.mdx and
// graph.mdx — it never clears other subdirectories, so the guides/ and usage/
// folders we place here survive the build.
//
// Both sets are authored as plain Markdown (the same source a human reads in the
// repo) and become MDX here. Docusaurus's autogenerated `guidesSidebar` and
// `usageSidebar` pick them up via each folder's _category_.json.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
// The sdd-content plugin and the Docusaurus docs plugin both resolve the
// generated docs tree relative to siteDir (docs-site/) as '../docs-generated'
// — i.e. the repo-root docs-generated/ sibling of docs-site/. This script lives
// in docs-site/scripts/, so the repo root is two levels up. Match the plugins
// exactly, so the copied docs land in the same tree the docs plugin reads.
const destDir = path.resolve(here, '../../docs-generated');

// Guides first: they are the 0-to-1 path a new reader starts on.
const sections = [
  { dir: 'guides', label: 'Getting started', position: 2 },
  { dir: 'usage', label: 'Usage', position: 3 },
];

for (const { dir, label, position } of sections) {
  const srcDir = path.resolve(here, '../../docs', dir);
  const outDir = path.join(destDir, dir);
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  for (const file of fs.readdirSync(srcDir)) {
    if (!file.endsWith('.md')) continue;
    fs.copyFileSync(path.join(srcDir, file), path.join(outDir, file.replace(/\.md$/, '.mdx')));
  }
  fs.writeFileSync(path.join(outDir, '_category_.json'), JSON.stringify({ label, position }, null, 2));
  console.log(`[copy-usage] copied ${dir} docs →`, outDir);
}
