#!/usr/bin/env node
// Copy the hand-authored usage docs (../../docs/usage/*.md) into the generated
// Docusaurus docs tree (build output). The sdd-content plugin owns ../docs-generated
// but only writes decisions/, specs/, index.mdx and graph.mdx — it never clears
// other subdirectories, so a usage/ folder we place here survives the build.
//
// The usage docs are authored as plain Markdown (the same source a human reads in
// the repo) and become MDX here. Docusaurus's autogenerated `usageSidebar` picks
// them up via usage/_category_.json.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const docsDir = path.resolve(here, '../../docs/usage');
// The sdd-content plugin and the Docusaurus docs plugin both resolve the
// generated docs tree relative to siteDir (docs-site/) as '../docs-generated'
// — i.e. the repo-root docs-generated/ sibling of docs-site/. This script lives
// in docs-site/scripts/, so the repo root is two levels up. Match the plugins
// exactly, so the usage docs land in the same tree the docs plugin reads.
const destDir = path.resolve(here, '../../docs-generated');

fs.rmSync(path.join(destDir, 'usage'), { recursive: true, force: true });
fs.mkdirSync(path.join(destDir, 'usage'), { recursive: true });

for (const file of fs.readdirSync(docsDir)) {
  if (!file.endsWith('.md')) continue;
  const src = path.join(docsDir, file);
  const dest = path.join(destDir, 'usage', file.replace(/\.md$/, '.mdx'));
  fs.copyFileSync(src, dest);
}
console.log('[copy-usage] copied usage docs →', path.join(destDir, 'usage'));

fs.writeFileSync(
  path.join(destDir, 'usage', '_category_.json'),
  JSON.stringify({ label: 'Usage', position: 3 }, null, 2),
);
