package main

// Plain-output pins for `harness logs`.
//
// Scripts and agents parse what `harness logs` prints to a pipe, so the plain
// form is a contract: these goldens were generated by the renderer as it stood
// before the styled terminal view existed (origin/main at 3a0f05c) and must
// keep passing byte for byte. They use only functions that predate the styled
// view, so the same file runs against that commit.

import (
	"bytes"
	"testing"

	"github.com/stump-wtf/harness/internal/protocol"
)

// repeatingErrors is postMortem with the error mark repeated, as a provider
// retry loop writes it — the shape the styled view collapses and the plain
// view must not.
func repeatingErrors() protocol.LogsData {
	ld := postMortem()
	tail := ld.Entries[len(ld.Entries)-1]
	ld.Entries = ld.Entries[:len(ld.Entries)-1]
	for i, s := range []int{21, 22, 23} {
		ld.Entries = append(ld.Entries, protocol.LogEntry{
			ID: "rep" + string(rune('a'+i)), Time: stampAt(7, 56, s), Kind: protocol.LogEntryMark,
			Action: "error", Summary: "Bad Request: litellm.ContextWindowExceededError",
		})
	}
	ld.Entries = append(ld.Entries, tail,
		protocol.LogEntry{ID: "amb", Time: stampAt(7, 56, 22), Kind: protocol.LogEntryTool, Action: "exec", Summary: "gh pr list", Ambiguous: true})
	ld.Notices = []string{"1 session(s) in this run's window not shown"}
	return ld
}

const repeatingErrorsPlain = "run 2026-09-11 07:40:00 → 07:56:21 · exit 1 · crush · /home/agent/sweeps\n" +
	"          note      1 session(s) in this run's window not shown\n" +
	"07:40:00  state     stopped → starting\n" +
	"07:40:02  session   e088ec4e · crush · litellm/Qwen3.8-27B\n" +
	"07:40:05  read      /home/agent/.config/dotfiles/stumpcloud-sweep.prompt.md\n" +
	"07:41:10  exec      ssh nuc01 docker ps  (failed)\n" +
	"07:56:20  ERROR     Bad Request: litellm.ContextWindowExceededError[31m\n" +
	"07:56:21  ERROR     Bad Request: litellm.ContextWindowExceededError\n" +
	"07:56:22  ERROR     Bad Request: litellm.ContextWindowExceededError\n" +
	"07:56:23  ERROR     Bad Request: litellm.ContextWindowExceededError\n" +
	"07:56:21  exited    code=1\n" +
	"07:56:22  ?exec     gh pr list\n"

// TestPlainActivityIsByteIdentical: the non-terminal activity view prints
// every entry, repeats included, with no styling — exactly as before.
func TestPlainActivityIsByteIdentical(t *testing.T) {
	var buf bytes.Buffer
	renderActivity(&buf, repeatingErrors())
	if got := buf.String(); got != repeatingErrorsPlain {
		t.Errorf("plain activity view changed\n--- got ---\n%s--- want ---\n%s", got, repeatingErrorsPlain)
	}
}

// TestPlainRawIsByteIdentical: the non-terminal raw view prints the daemon's
// lines and the agent's output exactly as the durable log holds them.
func TestPlainRawIsByteIdentical(t *testing.T) {
	raw := "2026/09/25 20:14:36 INFO state changed from=restarting to=starting\n" +
		"Error: You must be logged in to use Remote Control.\n" +
		"2026/09/25 20:14:36 INFO exited code=1\n" +
		"2026/09/25 20:15:16 WARN run interrupted run_id=7 reason=\"the daemon exited\""
	var buf bytes.Buffer
	printLogText(&buf, raw)
	if got, want := buf.String(), raw+"\n"; got != want {
		t.Errorf("plain raw view changed\n--- got ---\n%q\n--- want ---\n%q", got, want)
	}
}
